### ISSUE TITLE
Does this library still works ?

### ISSUE THREAD

**Issue by erick-escape** [luoxiaojun1992/laravel-presto#1]
I need a library that integrates Presto with Laravel to use Eloquent instead of Presto's raw queries. I found this one, but I'm not sure if it works properly because it doesn't even have a README completed

**Comment by luoxiaojun1992** [comment]
> I need a library that integrates Presto with Laravel to use Eloquent instead of Presto's raw queries. I found this one, but I'm not sure if it works properly because it doesn't even have a README completed

Sorry, I'm not sure the library is compatible with your Laravel. The library was developed for Laravel 5.5. Maybe you can try it because the code is simple, and feel free to fork, contribute code or submit PR.

**Comment by erick-escape** [comment]
It happens that my project was built using Laravel 5.5. I installed the library and try it out, but no success. I'm using ODBC connection to access data through Amazon Athena. In the connection configuration I have something like:

'odbc' => [
    'driver'   => 'odbc',
    'dsn'      => env('ODBC_DSN'),
    'host'     => env('ODBC_HOST'),
    'database' => env('ODBC_DB'),
    'username' => env('ODBC_USERNAME'),
    'password' => env('ODBC_PASSWORD'),
],

What I'm trying to do is to add the 'grammar' in this configuration, it would be something like:
'odbc' => [
    'driver'   => 'odbc',
    'dsn'      => env('ODBC_DSN'),
    'host'     => env('ODBC_HOST'),
    'database' => env('ODBC_DB'),
    'username' => env('ODBC_USERNAME'),
    'password' => env('ODBC_PASSWORD'),
    'grammar' => [
        'query' => Illuminate\Database\Query\Grammars\SqlServerGrammar::class,
        'schema' => Illuminate\Database\Schema\Grammars\SqlServerGrammar::class,
    ],

When I installed the library I just replaced the paths to: Lxj\Laravel\Presto\Query\Grammars\Grammar::class in 'query' and Lxj\Laravel\Presto\Schema\Grammars\Grammar::class in 'schema', but when I tried to make a consult using Eloquent it failed. It couldn't connect to the Amazon Athena server.

**Comment by luoxiaojun1992** [comment]
> It happens that my project was built using Laravel 5.5. I installed the library and try it out, but no success. I'm using ODBC connection to access data through Amazon Athena. In the connection configuration I have something like:
> 
> 'odbc' => [ 'driver' => 'odbc', 'dsn' => env('ODBC_DSN'), 'host' => env('ODBC_HOST'), 'database' => env('ODBC_DB'), 'username' => env('ODBC_USERNAME'), 'password' => env('ODBC_PASSWORD'), ],
> 
> What I'm trying to do is to add the 'grammar' in this configuration, it would be something like: 'odbc' => [ 'driver' => 'odbc', 'dsn' => env('ODBC_DSN'), 'host' => env('ODBC_HOST'), 'database' => env('ODBC_DB'), 'username' => env('ODBC_USERNAME'), 'password' => env('ODBC_PASSWORD'), 'grammar' => [ 'query' => Illuminate\Database\Query\Grammars\SqlServerGrammar::class, 'schema' => Illuminate\Database\Schema\Grammars\SqlServerGrammar::class, ],
> 
> When I installed the library I just replaced the paths to: Lxj\Laravel\Presto\Query\Grammars\Grammar::class in 'query' and Lxj\Laravel\Presto\Schema\Grammars\Grammar::class in 'schema', but when I tried to make a consult using Eloquent it failed. It couldn't connect to the Amazon Athena server.

ODBC driver is not supported by the library.

You can try the configuration like:
```
'presto' => [
        'driver' => 'presto',
        'host' => 'http://xxxx:32719/',
        'catalog' => 'kudu',
        'schema' => 'default',
        'prefix' => 'impala::default.',
],
```
